# Generated by Django 6.0.6 on 2026-07-08 17:12
# flake8: noqa: E501

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True,
                 max_length=255, verbose_name='Country')),
                ('city', models.CharField(blank=True,
                 max_length=255, verbose_name='City')),
                ('preferred_language', models.CharField(blank=True,
                 max_length=255, verbose_name='Preferred language')),
                ('car_brand', models.CharField(blank=True,
                 max_length=255, verbose_name='Car brand')),
                ('car_model', models.CharField(blank=True,
                 max_length=255, verbose_name='Car model')),
                ('car_year', models.PositiveIntegerField(
                    blank=True, null=True, verbose_name='Car year')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'users_profile',
                'ordering': ('id',),
            },
        ),
    ]
