# Generated by Django 6.0.6 on 2026-07-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('user', 'Пользователь'), ('premium', 'Премиум'), ('moderator', 'Модератор')], default='user', help_text='Роль пользователя в системе.', max_length=20, verbose_name='Role'),
        ),
    ]
