# Generated by Django 6.0.6 on 2026-07-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_repairhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('premium', 'Премиум'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', help_text='Роль пользователя в системе.', max_length=20, verbose_name='Role'),
        ),
    ]
