# Generated by Django 6.0.6 on 2026-07-12 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0002_compatibility_oemnumber_partimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(help_text='SEO-friendly URL.', max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tool category',
                'verbose_name_plural': 'Tool categories',
                'db_table': 'tools_toolcategory',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('size', models.CharField(blank=True, max_length=255, verbose_name='Size')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tools/images/', verbose_name='Image')),
                ('amazon_url', models.URLField(blank=True, max_length=1000, verbose_name='Amazon URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='tools.toolcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'db_table': 'tools_tool',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PartTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True, help_text='Indicates whether this tool is required.', verbose_name='Required')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_tools', to='parts.part', verbose_name='Part')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_parts', to='tools.tool', verbose_name='Tool')),
            ],
            options={
                'verbose_name': 'Part tool',
                'verbose_name_plural': 'Part tools',
                'db_table': 'parts_parttool',
                'ordering': ('part', 'tool'),
                'constraints': [models.UniqueConstraint(fields=('part', 'tool'), name='uq_part_tool')],
            },
        ),
    ]
