# Generated by Django 6.0.6 on 2026-07-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='amazon_url',
        ),
        migrations.AddField(
            model_name='tool',
            name='ozon_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Ozon URL'),
        ),
    ]
