# Generated by Django 6.0.6 on 2026-07-12 15:48
# flake8: noqa: E501

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(
                    upload_to='instructions/images/', verbose_name='Image')),
                ('description', models.TextField(
                    blank=True, help_text='Description of the image or the illustrated step.', verbose_name='Description')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='images', to='instructions.instruction', verbose_name='Instruction')),
            ],
            options={
                'verbose_name': 'Instruction image',
                'verbose_name_plural': 'Instruction images',
                'db_table': 'instructions_instructionimage',
                'ordering': ('instruction', 'id'),
            },
        ),
        migrations.CreateModel(
            name='InstructionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(
                    help_text='Sequential number of the instruction step.', verbose_name='Step number')),
                ('title', models.CharField(blank=True,
                 max_length=255, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('warning', models.TextField(
                    blank=True, help_text='Important safety information or recommendations.', verbose_name='Warning')),
                ('estimated_minutes', models.PositiveIntegerField(
                    blank=True, help_text='Estimated time to complete this step.', null=True, verbose_name='Estimated minutes')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='steps', to='instructions.instruction', verbose_name='Instruction')),
            ],
            options={
                'verbose_name': 'Instruction step',
                'verbose_name_plural': 'Instruction steps',
                'db_table': 'instructions_instructionstep',
                'ordering': ('instruction', 'step_number'),
            },
        ),
        migrations.CreateModel(
            name='InstructionTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_description', models.TextField(
                    blank=True, help_text='Description of how this tool is used in the instruction.', verbose_name='Usage description')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='instruction_tools', to='instructions.instruction', verbose_name='Instruction')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='instruction_tools', to='tools.tool', verbose_name='Tool')),
            ],
            options={
                'verbose_name': 'Instruction tool',
                'verbose_name_plural': 'Instruction tools',
                'db_table': 'instructions_instructiontool',
                'ordering': ('instruction', 'tool'),
            },
        ),
        migrations.CreateModel(
            name='InstructionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(
                    verbose_name='Version number')),
                ('content', models.TextField(verbose_name='Content')),
                ('changelog', models.TextField(
                    blank=True, help_text='Description of changes made in this version.', verbose_name='Changelog')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created at')),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='versions', to='instructions.instruction', verbose_name='Instruction')),
            ],
            options={
                'verbose_name': 'Instruction version',
                'verbose_name_plural': 'Instruction versions',
                'db_table': 'instructions_instructionversion',
                'ordering': ('-version_number',),
            },
        ),
    ]
