# Generated by Django 6.0.6 on 2026-07-12 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('duration_days', models.PositiveIntegerField(help_text='Subscription duration in days.', verbose_name='Duration (days)')),
                ('max_ai_requests', models.PositiveIntegerField(default=0, help_text='Maximum number of AI requests available within the subscription.', verbose_name='Maximum AI requests')),
                ('has_chat_access', models.BooleanField(default=False, help_text='Allows access to the AI chat.', verbose_name='Chat access')),
                ('has_image_analysis', models.BooleanField(default=False, help_text='Allows using AI image analysis.', verbose_name='Image analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Subscription plan',
                'verbose_name_plural': 'Subscription plans',
                'db_table': 'subscriptions_subscriptionplan',
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('auto_renew', models.BooleanField(default=False, help_text='Automatically renew the subscription after expiration.', verbose_name='Auto renew')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='Subscription plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User subscription',
                'verbose_name_plural': 'User subscriptions',
                'db_table': 'subscriptions_usersubscription',
                'ordering': ('-end_date',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=100, verbose_name='Payment provider')),
                ('external_payment_id', models.CharField(blank=True, help_text='Payment identifier returned by the payment provider.', max_length=255, verbose_name='External payment ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='Currency')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Payment status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscriptions.usersubscription', verbose_name='Subscription')),
            ],
            options={
                'verbose_name': 'Subscription payment',
                'verbose_name_plural': 'Subscription payments',
                'db_table': 'subscriptions_subscriptionpayment',
                'ordering': ('-paid_at', '-id'),
            },
        ),
    ]
