# Generated by Django 6.0.6 on 2026-07-11 17:27
# flake8: noqa: E501

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(help_text='SEO-friendly URL.',
                 max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(
                    blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Part category',
                'verbose_name_plural': 'Part categories',
                'db_table': 'parts_partcategory',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(help_text='SEO-friendly URL.',
                 max_length=255, unique=True, verbose_name='Slug')),
                ('original_number', models.CharField(db_index=True,
                 max_length=255, verbose_name='Original number')),
                ('manufacturer', models.CharField(blank=True,
                 max_length=255, verbose_name='Manufacturer')),
                ('description', models.TextField(
                    blank=True, verbose_name='Description')),
                ('seo_title', models.CharField(blank=True,
                 max_length=255, verbose_name='SEO title')),
                ('seo_description', models.TextField(
                    blank=True, verbose_name='SEO description')),
                ('seo_keywords', models.TextField(
                    blank=True, verbose_name='SEO keywords')),
                ('weight', models.DecimalField(blank=True, decimal_places=2,
                 max_digits=10, null=True, verbose_name='Weight')),
                ('dimensions', models.JSONField(
                    blank=True, help_text='Part dimensions in JSON format.', null=True, verbose_name='Dimensions')),
                ('is_active', models.BooleanField(
                    default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='parts', to='parts.partcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'db_table': 'parts_part',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['original_number'], name='parts_part_index_for_original_number')],
            },
        ),
    ]
