# Generated by Django 6.0.6 on 2026-07-12 15:48
# flake8: noqa: E501

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True,
                 max_length=255, verbose_name='Brand')),
                ('model', models.CharField(blank=True,
                 max_length=255, verbose_name='Model')),
                ('generation', models.CharField(blank=True,
                 max_length=255, verbose_name='Generation')),
                ('engine', models.CharField(blank=True,
                 max_length=255, verbose_name='Engine')),
                ('year_from', models.PositiveIntegerField(
                    blank=True, null=True, verbose_name='Year from')),
                ('year_to', models.PositiveIntegerField(
                    blank=True, null=True, verbose_name='Year to')),
            ],
            options={
                'verbose_name': 'Compatibility',
                'verbose_name_plural': 'Compatibilities',
                'db_table': 'parts_compatibility',
                'ordering': ('brand', 'model', 'generation', 'year_from'),
            },
        ),
        migrations.CreateModel(
            name='OEMNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255,
                 unique=True, verbose_name='OEM number')),
                ('manufacturer', models.CharField(blank=True,
                 max_length=255, verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'OEM number',
                'verbose_name_plural': 'OEM numbers',
                'db_table': 'parts_oemnumber',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(
                    upload_to='parts/images/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for SEO and accessibility.',
                 max_length=255, verbose_name='Alternative text')),
                ('is_main', models.BooleanField(default=False,
                 help_text='Indicates whether this image is the primary image for the part.', verbose_name='Main image')),
                ('uploaded_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Uploaded at')),
            ],
            options={
                'verbose_name': 'Part image',
                'verbose_name_plural': 'Part images',
                'db_table': 'parts_partimage',
                'ordering': ('-is_main', 'id'),
            },
        ),
        migrations.RenameIndex(
            model_name='part',
            new_name='part_original_oem_idx',
            old_name='parts_part_index_for_original_number',
        ),
        migrations.AddField(
            model_name='compatibility',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='compatibilities', to='parts.part', verbose_name='Part'),
        ),
        migrations.AddField(
            model_name='oemnumber',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='oem_numbers', to='parts.part', verbose_name='Part'),
        ),
        migrations.AddField(
            model_name='partimage',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='images', to='parts.part', verbose_name='Part'),
        ),
        migrations.AddConstraint(
            model_name='oemnumber',
            constraint=models.UniqueConstraint(
                fields=('part', 'number'), name='parts_oemnumber_index_0'),
        ),
    ]
