# Generated by Django 6.0.6 on 2026-07-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_compatibility_oemnumber_partimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='normalized_original_number',
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                max_length=255,
                verbose_name='Normalized original number'),
        ),
    ]
