# Generated by Django 6.0.6 on 2026-07-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_part_normalized_original_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='dimensions',
            field=models.JSONField(blank=True, help_text='Part sizes in JSON format.', null=True, verbose_name='Sizes'),
        ),
    ]
