from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.instructions.models import Instruction
from apps.parts.models import Part


class AIRequest(models.Model):
    """
    Модель запроса к искусственному интеллекту.

    Хранит историю обращений пользователя к AI-сервису.
    Содержит текст запроса, ответ модели, информацию
    о количестве использованных токенов, типе запроса
    и связанную автомобильную запчасть, если она
    использовалась при обработке запроса.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="ai_requests",
        verbose_name=_("User"),
    )

    part = models.ForeignKey(
        Part,
        on_delete=models.SET_NULL,
        related_name="ai_requests",
        null=True,
        blank=True,
        verbose_name=_("Part"),
    )

    prompt = models.TextField(
        verbose_name=_("Prompt"),
        help_text=_("User request sent to the AI service."),
    )

    response = models.TextField(
        blank=True,
        verbose_name=_("Response"),
        help_text=_("Response generated by the AI service."),
    )

    tokens_used = models.PositiveIntegerField(
        default=0,
        verbose_name=_("Tokens used"),
    )

    request_type = models.CharField(
        max_length=100,
        blank=True,
        verbose_name=_("Request type"),
        help_text=_("Type of AI request."),
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Created at"),
    )

    class Meta:
        db_table = "ai_airequest"
        ordering = ("-created_at",)
        verbose_name = _("AI request")
        verbose_name_plural = _("AI requests")

    def __str__(self):
        return f"{self.user.email} — {self.created_at:%d.%m.%Y %H:%M}"


class AIGeneratedInstruction(models.Model):
    """
    Модель инструкции, сгенерированной искусственным интеллектом.

    Хранит результат генерации инструкции на основе запроса
    пользователя к AI. Позволяет сохранить сгенерированный текст
    и при необходимости связать его с опубликованной инструкцией.
    """

    ai_request = models.OneToOneField(
        AIRequest,
        on_delete=models.CASCADE,
        related_name="generated_instruction",
        verbose_name=_("AI request"),
    )

    instruction = models.ForeignKey(
        Instruction,
        on_delete=models.SET_NULL,
        related_name="generated_versions",
        null=True,
        blank=True,
        verbose_name=_("Instruction"),
    )

    generated_content = models.TextField(
        verbose_name=_("Generated content"),
        help_text=_("Instruction content generated by the AI service."),
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Created at"),
    )

    class Meta:
        db_table = "ai_aigeneratedinstruction"
        ordering = ("-created_at",)
        verbose_name = _("AI generated instruction")
        verbose_name_plural = _("AI generated instructions")

    def __str__(self):
        return (
            f"{_('AI instruction')} "
            f"#{self.pk}"
        )


class AIImageAnalysis(models.Model):
    """
    Модель анализа изображения искусственным интеллектом.

    Хранит результаты анализа изображений, загруженных
    пользователями. Позволяет сохранить исходное изображение,
    определенную AI запчасть, уровень уверенности распознавания
    и полный результат анализа в формате JSON.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="image_analyses",
        verbose_name=_("User"),
    )

    image = models.ImageField(
        upload_to="ai/image_analysis/",
        verbose_name=_("Image"),
    )

    detected_part = models.ForeignKey(
        Part,
        on_delete=models.SET_NULL,
        related_name="image_analyses",
        null=True,
        blank=True,
        verbose_name=_("Detected part"),
    )

    confidence_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        verbose_name=_("Confidence score"),
        help_text=_("Confidence level of the detected part."),
    )

    analysis_result = models.JSONField(
        null=True,
        blank=True,
        verbose_name=_("Analysis result"),
        help_text=_("Full AI analysis result in JSON format."),
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Created at"),
    )

    class Meta:
        db_table = "ai_aiimageanalysis"
        ordering = ("-created_at",)
        verbose_name = _("AI image analysis")
        verbose_name_plural = _("AI image analyses")

    def __str__(self):
        return (
            f"{self.user.email} — "
            f"{_('Analysis')} #{self.pk}"
        )
