from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.instructions.models import Instruction
from apps.parts.models import Part


class AIRequest(models.Model):
    """
    Модель запроса к искусственному интеллекту.

    Хранит историю обращений пользователя к AI-сервису.
    Содержит текст запроса, ответ модели, информацию
    о количестве использованных токенов, типе запроса
    и связанную автомобильную запчасть, если она
    использовалась при обработке запроса.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="ai_requests",
        verbose_name=_("User"),
    )

    part = models.ForeignKey(
        Part,
        on_delete=models.SET_NULL,
        related_name="ai_requests",
        null=True,
        blank=True,
        verbose_name=_("Part"),
    )

    prompt = models.TextField(
        verbose_name=_("Prompt"),
        help_text=_("User request sent to the AI service."),
    )

    response = models.TextField(
        blank=True,
        verbose_name=_("Response"),
        help_text=_("Response generated by the AI service."),
    )

    tokens_used = models.PositiveIntegerField(
        default=0,
        verbose_name=_("Tokens used"),
    )

    request_type = models.CharField(
        max_length=100,
        blank=True,
        verbose_name=_("Request type"),
        help_text=_("Type of AI request."),
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Created at"),
    )

    class Meta:
        db_table = "ai_airequest"
        ordering = ("-created_at",)
        verbose_name = _("AI request")
        verbose_name_plural = _("AI requests")

    def __str__(self):
        return f"{self.user.email} — {self.created_at:%d.%m.%Y %H:%M}"


class AIGeneratedInstruction(models.Model):
    """
    Модель инструкции, сгенерированной искусственным интеллектом.

    Хранит результат генерации инструкции на основе запроса
    пользователя к AI. Позволяет сохранить сгенерированный текст
    и при необходимости связать его с опубликованной инструкцией.
    """

    ai_request = models.OneToOneField(
        AIRequest,
        on_delete=models.CASCADE,
        related_name="generated_instruction",
        verbose_name=_("AI request"),
    )

    instruction = models.ForeignKey(
        Instruction,
        on_delete=models.SET_NULL,
        related_name="generated_versions",
        null=True,
        blank=True,
        verbose_name=_("Instruction"),
    )

    generated_content = models.TextField(
        verbose_name=_("Generated content"),
        help_text=_("Instruction content generated by the AI service."),
    )

    class ModerationStatus(models.TextChoices):
        PENDING = "pending", _("Pending moderation")
        APPROVED = "approved", _("Approved")
        REJECTED = "rejected", _("Rejected")

    version_number = models.PositiveIntegerField(
        default=1,
        verbose_name=_("Version number"),
        help_text=_(
            "Published or proposed instruction version returned to the user."
        ),
    )

    is_cached = models.BooleanField(
        default=False,
        verbose_name=_("Returned from cache"),
        help_text=_(
            "The saved published instruction was returned without regeneration."
        ),
    )

    moderation_status = models.CharField(
        max_length=20,
        choices=ModerationStatus.choices,
        default=ModerationStatus.PENDING,
        db_index=True,
        verbose_name=_("Moderation status"),
    )

    moderation_note = models.TextField(
        blank=True,
        verbose_name=_("Moderation note"),
    )

    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name="reviewed_ai_instructions",
        null=True,
        blank=True,
        verbose_name=_("Reviewed by"),
    )

    reviewed_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("Reviewed at"),
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Created at"),
    )

    class Meta:
        db_table = "ai_aigeneratedinstruction"
        ordering = ("-created_at",)
        verbose_name = _("AI generated instruction")
        verbose_name_plural = _("AI generated instructions")

    def __str__(self):
        return (
            f"{_('AI instruction')} "
            f"#{self.pk}"
        )


class AIToolRecommendation(models.Model):
    """
    Модель модерируемой AI-рекомендации инструментов.

    Хранит ответ AI до решения технического модератора. Одобрение
    разрешает показывать рекомендацию пользователю, но намеренно не создаёт
    инструменты и связи PartTool автоматически: каталог остаётся источником
    только проверенных редакцией данных.
    """

    class ModerationStatus(models.TextChoices):
        PENDING = "pending", _("Pending moderation")
        APPROVED = "approved", _("Approved")
        REJECTED = "rejected", _("Rejected")

    ai_request = models.OneToOneField(
        AIRequest,
        on_delete=models.CASCADE,
        related_name="tool_recommendation",
        verbose_name=_("AI request"),
    )

    generated_content = models.TextField(
        verbose_name=_("Generated content"),
        help_text=_("Tool recommendation generated by the AI service."),
    )

    moderation_status = models.CharField(
        max_length=20,
        choices=ModerationStatus.choices,
        default=ModerationStatus.PENDING,
        db_index=True,
        verbose_name=_("Moderation status"),
    )

    moderation_note = models.TextField(
        blank=True,
        verbose_name=_("Moderation note"),
    )

    reviewed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        related_name="reviewed_ai_tool_recommendations",
        null=True,
        blank=True,
        verbose_name=_("Reviewed by"),
    )

    reviewed_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name=_("Reviewed at"),
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Created at"),
    )

    class Meta:
        db_table = "ai_aitoolrecommendation"
        ordering = ("-created_at",)
        verbose_name = _("AI tool recommendation")
        verbose_name_plural = _("AI tool recommendations")

    def __str__(self):
        return f"{_('AI tool recommendation')} #{self.pk}"


class AIContentPurchase(models.Model):
    """
    Фиксирует однократное приобретение AI-контента пользователем.

    Запись не зависит от последующей смены или продления тарифа. Она
    подтверждает, что первичная выдача была учтена в лимите подписки.
    """

    class ContentType(models.TextChoices):
        CHAT = "chat", _("AI chat response")
        INSTRUCTION = "instruction", _("Repair instruction")
        TOOLS = "tools", _("Tool selection")

    class Source(models.TextChoices):
        DATABASE = "database", _("Project database")
        AI = "ai", _("AI generation")

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="ai_content_purchases",
        verbose_name=_("User"),
    )
    subscription = models.ForeignKey(
        "subscriptions.UserSubscription",
        on_delete=models.SET_NULL,
        related_name="content_purchases",
        null=True,
        blank=True,
        verbose_name=_("Subscription"),
    )
    content_type = models.CharField(
        max_length=20,
        choices=ContentType.choices,
        db_index=True,
        verbose_name=_("Content type"),
    )
    content_key = models.CharField(
        max_length=160,
        verbose_name=_("Content key"),
        help_text=_("Stable identifier used to prevent a repeated purchase."),
    )
    part = models.ForeignKey(
        Part,
        on_delete=models.SET_NULL,
        related_name="ai_content_purchases",
        null=True,
        blank=True,
        verbose_name=_("Part"),
    )
    instruction = models.ForeignKey(
        Instruction,
        on_delete=models.SET_NULL,
        related_name="ai_content_purchases",
        null=True,
        blank=True,
        verbose_name=_("Instruction"),
    )
    source_request = models.ForeignKey(
        AIRequest,
        on_delete=models.SET_NULL,
        related_name="content_purchases",
        null=True,
        blank=True,
        verbose_name=_("Source AI request"),
    )
    source = models.CharField(
        max_length=20,
        choices=Source.choices,
        default=Source.AI,
        verbose_name=_("Content source"),
    )
    purchased_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Purchased at"),
    )
    last_accessed_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_("Last accessed at"),
    )

    class Meta:
        db_table = "ai_aicontentpurchase"
        ordering = ("-purchased_at",)
        verbose_name = _("AI content purchase")
        verbose_name_plural = _("AI content purchases")
        constraints = (
            models.UniqueConstraint(
                fields=("user", "content_type", "content_key"),
                name="ai_purchase_user_type_key_uniq",
            ),
        )
        indexes = (
            models.Index(
                fields=("user", "content_type", "part"),
                name="ai_purchase_user_part_idx",
            ),
            models.Index(
                fields=("user", "content_type", "instruction"),
                name="ai_purchase_user_instr_idx",
            ),
        )

    def __str__(self):
        return (
            f"{self.user.email} — "
            f"{self.get_content_type_display()} — {self.content_key}"
        )


class AIImageAnalysis(models.Model):
    """
    Модель анализа изображения искусственным интеллектом.

    Хранит результаты анализа изображений, загруженных
    пользователями. Позволяет сохранить исходное изображение,
    определенную AI запчасть, уровень уверенности распознавания
    и полный результат анализа в формате JSON.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="image_analyses",
        verbose_name=_("User"),
    )

    image = models.ImageField(
        upload_to="ai/image_analysis/",
        verbose_name=_("Image"),
    )

    detected_part = models.ForeignKey(
        Part,
        on_delete=models.SET_NULL,
        related_name="image_analyses",
        null=True,
        blank=True,
        verbose_name=_("Detected part"),
    )

    confidence_score = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        null=True,
        blank=True,
        verbose_name=_("Confidence score"),
        help_text=_("Confidence level of the detected part."),
    )

    analysis_result = models.JSONField(
        null=True,
        blank=True,
        verbose_name=_("Analysis result"),
        help_text=_("Full AI analysis result in JSON format."),
    )

    moderation_status = models.CharField(
        max_length=20,
        default="approved",
        editable=False,
        db_index=True,
        verbose_name=_("Automatic moderation status"),
        help_text=_(
            "Only images approved by automatic moderation are stored."
        ),
    )

    moderation_categories = models.JSONField(
        default=list,
        blank=True,
        editable=False,
        verbose_name=_("Moderation categories"),
    )

    moderation_model = models.CharField(
        max_length=100,
        blank=True,
        editable=False,
        verbose_name=_("Moderation model"),
    )

    moderation_checked_at = models.DateTimeField(
        null=True,
        blank=True,
        editable=False,
        verbose_name=_("Moderation checked at"),
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_("Created at"),
    )

    class Meta:
        db_table = "ai_aiimageanalysis"
        ordering = ("-created_at",)
        verbose_name = _("AI image analysis")
        verbose_name_plural = _("AI image analyses")

    def __str__(self):
        return (
            f"{self.user.email} — "
            f"{_('Analysis')} #{self.pk}"
        )
