# Generated by Django 6.0.6 on 2026-07-12 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructions', '0002_instructionimage_instructionstep_instructiontool_and_more'),
        ('parts', '0002_compatibility_oemnumber_partimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai/image_analysis/', verbose_name='Image')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence level of the detected part.', max_digits=5, null=True, verbose_name='Confidence score')),
                ('analysis_result', models.JSONField(blank=True, help_text='Full AI analysis result in JSON format.', null=True, verbose_name='Analysis result')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('detected_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_analyses', to='parts.part', verbose_name='Detected part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_analyses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI image analysis',
                'verbose_name_plural': 'AI image analyses',
                'db_table': 'ai_aiimageanalysis',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(help_text='User request sent to the AI service.', verbose_name='Prompt')),
                ('response', models.TextField(blank=True, help_text='Response generated by the AI service.', verbose_name='Response')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='Tokens used')),
                ('request_type', models.CharField(blank=True, help_text='Type of AI request.', max_length=100, verbose_name='Request type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='parts.part', verbose_name='Part')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'AI request',
                'verbose_name_plural': 'AI requests',
                'db_table': 'ai_airequest',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_content', models.TextField(help_text='Instruction content generated by the AI service.', verbose_name='Generated content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_versions', to='instructions.instruction', verbose_name='Instruction')),
                ('ai_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_instruction', to='AI.airequest', verbose_name='AI request')),
            ],
            options={
                'verbose_name': 'AI generated instruction',
                'verbose_name_plural': 'AI generated instructions',
                'db_table': 'ai_aigeneratedinstruction',
                'ordering': ('-created_at',),
            },
        ),
    ]
