# Generated by Django 6.0.6 on 2026-07-25 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0002_aigeneratedinstruction_moderation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimageanalysis',
            name='moderation_categories',
            field=models.JSONField(blank=True, default=list, editable=False, verbose_name='Moderation categories'),
        ),
        migrations.AddField(
            model_name='aiimageanalysis',
            name='moderation_checked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Moderation checked at'),
        ),
        migrations.AddField(
            model_name='aiimageanalysis',
            name='moderation_model',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Moderation model'),
        ),
        migrations.AddField(
            model_name='aiimageanalysis',
            name='moderation_status',
            field=models.CharField(db_index=True, default='approved', editable=False, help_text='Only images approved by automatic moderation are stored.', max_length=20, verbose_name='Automatic moderation status'),
        ),
        migrations.CreateModel(
            name='AIToolRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_content', models.TextField(help_text='Tool recommendation generated by the AI service.', verbose_name='Generated content')),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending moderation'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Moderation status')),
                ('moderation_note', models.TextField(blank=True, verbose_name='Moderation note')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('ai_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tool_recommendation', to='AI.airequest', verbose_name='AI request')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_tool_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
            ],
            options={
                'verbose_name': 'AI tool recommendation',
                'verbose_name_plural': 'AI tool recommendations',
                'db_table': 'ai_aitoolrecommendation',
                'ordering': ('-created_at',),
            },
        ),
    ]
