# Generated by Django 6.0.6 on 2026-07-12 18:05
# flake8: noqa: E501

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0002_compatibility_oemnumber_partimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('searches_count', models.PositiveIntegerField(
                    default=0, help_text='Total number of searches for the part.', verbose_name='Searches count')),
                ('views_count', models.PositiveIntegerField(
                    default=0, help_text='Total number of views for the part.', verbose_name='Views count')),
                ('updated_at', models.DateTimeField(
                    auto_now=True, verbose_name='Updated at')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='popularity_statistics', to='parts.part', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Popular part',
                'verbose_name_plural': 'Popular parts',
                'db_table': 'analytics_popularpart',
                'ordering': ('-searches_count', '-views_count'),
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, help_text='Search query entered by the user.',
                 max_length=255, verbose_name='Search query')),
                ('results_count', models.PositiveIntegerField(
                    default=0, help_text='Number of search results returned.', verbose_name='Results count')),
                ('ip_address', models.GenericIPAddressField(blank=True,
                 null=True, unpack_ipv4=True, verbose_name='IP address')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Search log',
                'verbose_name_plural': 'Search logs',
                'db_table': 'analytics_searchlog',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(
                    blank=True, help_text='Name or type of the performed action.', max_length=255, verbose_name='Action')),
                ('metadata', models.JSONField(
                    blank=True, help_text='Additional information about the performed action in JSON format.', null=True, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User activity',
                'verbose_name_plural': 'User activities',
                'db_table': 'analytics_useractivity',
                'ordering': ('-created_at',),
            },
        ),
    ]
