# Generated by Django 6.0.6 on 2026-07-12 17:29
# flake8: noqa: E501

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_private', models.BooleanField(default=False,
                 help_text='Indicates whether the chat room is private.', verbose_name='Private')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                 related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Chat room',
                'verbose_name_plural': 'Chat rooms',
                'db_table': 'chat_chatroom',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_edited', models.BooleanField(default=False,
                 help_text='Indicates whether the message has been edited.', verbose_name='Edited')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='messages', to='chat.chatroom', verbose_name='Chat room')),
            ],
            options={
                'verbose_name': 'Chat message',
                'verbose_name_plural': 'Chat messages',
                'db_table': 'chat_chatmessage',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='Joined at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='chat_participations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='participants', to='chat.chatroom', verbose_name='Chat room')),
            ],
            options={
                'verbose_name': 'Chat participant',
                'verbose_name_plural': 'Chat participants',
                'db_table': 'chat_chatparticipant',
                'ordering': ('room', 'user'),
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='uq_room_user')],
            },
        ),
    ]
